CREATE TABLE CLINIC (
    id UUID NOT NULL,
    code BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
        DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),

    CONSTRAINT pk_clinic PRIMARY KEY (id),
    CONSTRAINT uk_clinic_code UNIQUE (code)
);
