CREATE TABLE IF NOT EXISTS SCHEDULING (
     id BINARY(16) NOT NULL,
    patient_id  BINARY(16) NOT NULL,

    pathology JSON NOT NULL,

    date_scheduling DATETIME NOT NULL,
    hours TIME NOT NULL,

    status ENUM('AGENDADO', 'CANCELADO', 'FINALIZADO') NOT NULL DEFAULT 'AGENDADO',

    variant VARCHAR(50),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),

    CONSTRAINT fk_scheduling_patient
        FOREIGN KEY (patient_id)
        REFERENCES PATIENT(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
